name: Tarea DAW03

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io

jobs:
  # 1 JOB
  phplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Lint PHP files
        uses: J3-Tech/PHP-Lint-Action@v0.0.5
        with: 
          path: .
          exclude: vendor

      - name: Setup PHP with PHPUnit installed globally
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpunit
  
      - name: Run PHPUnit tests
        run: phpunit --configuration phpunit.xml

  # JOB 2: Build and push image to GitHub Container Registry
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/sanprugit/daw:calculator-backend-latest


  # JOB 3: Build and push image to Docker Hub
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest

    permissions:
        packages: write
        contents: read
        attestations: write
        id-token: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/calculator-backend:latest